### ISSUE TITLE
What's this exec for?

### ISSUE THREAD

**Issue by stwomack** [neillturner/puppet-pm2#3]
https://github.com/neillturner/puppet-pm2/blob/master/manifests/init.pp#L73

In PE 3.7/3.8, the exec seems to happen first, which is perplexing enough. Because I'm not sure what the point of it is, I removed it from my fork and it seems to at least get past the error I was getting:

"Error: Failed to apply catalog: Validation of Exec[pm2 init] failed: 'pm2 status' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppetlabs/puppet/environments/sand/modules/pm2/manifests/init.pp:73"

However, if it really is needed, then I'll need to revisit.

**Comment by neillturner** [comment]
Thanks for posting this. I don't think it is super important. My puppet script has some workarounds for pm2 which maybe fixed in later versions. The current script worked recently for me although we are using puppet apply ans sinopia so probably didn't get the latest pm2 modile. I just need to find some time to test with the latest version of pm2.
